Pam\AccountBundle\Entity\Account:
    type: entity
    table: accounts
    repositoryClass: Pam\AccountBundle\Entity\AccountRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            lenght: '255'
        balance:
            type: decimal
            nullable: ture

    oneToMany:
        income:
            targetEntity: Transfer
            mappedBy: toAccount
        expence:
            targetEntity: Transfer
            mappedBy: fromAccount
    manyToOne:
        type:
            targetEntity: Type
            inversedBy: accounts
        user:
            targetEntity: User
            inversedBy: accounts
    lifecycleCallbacks: {  }
