Pam\AccountBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: Pam\AccountBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            lenght: '100'
        name:
            type: string
            lenght: '255'
            nullable: true
        email:
            type: string
            lenght: '255'
            nullable: true
    oneToMany:
        accounts:
            targetEntity: Account
            mappedBy: user
        transfers:
            targetEntity: Transfer
            mappedBy: user
    lifecycleCallbacks: {  }
