parameters:
#    pam_account.example.class: Pam\AccountBundle\Example

services:
#    pam_account.example:
#        class: %pam_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
